version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: hotels
      POSTGRES_USER: hotels
      POSTGRES_PASSWORD: hotels
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: